### ISSUE TITLE
Question (Feature Request)

### ISSUE THREAD

**Issue by enj5oy** [coffeegist/bofhound#3]
Hi, i use function NetSessionEnum on remote computer, or i enum Local Groups in remote computer how i can upload this info to bloodhound,  any idea how  i can parse this with bofhound?

**Comment by Tw1sm** [comment]
This is something we've talked about implementing before, but have not attempted or tested. Potentially could parse data from the CS-Situational-Awareness-BOF collection's `netloggedon` and `netsession` BOFs.

At a minimum this would require 
- additional parsing logic (BOF output won't match the `ldapsearch` output format
- additional processing logic (session/logged on results will have to get tied back to a computer object queried from LDAP)
- slight tweak to output JSON to include the new relationships

**Comment by Tw1sm** [comment]
This was added in #4 and the corresponding BOFs that can be parsed by BOFHound can be found in this [PR](https://github.com/trustedsec/CS-Situational-Awareness-BOF/pull/114) to the CS-Situational-Awareness-BOF repo

**Comment by Tw1sm** [comment]
Some additional info on how to actually perform these actions can be found here [https://posts.specterops.io/bofhound-session-integration-7b88b6f18423](https://posts.specterops.io/bofhound-session-integration-7b88b6f18423)
