### ISSUE TITLE
Still cant  import computers.json to old bloodhound 4.3.1

### ISSUE THREAD

**Issue by Hexix23** [coffeegist/bofhound#7]
Hi team,

I know that the issue was open on #2 but I intalled `bofhound <= 0.2.0` and im using bloodhound 4.3.1 legacy and I cannot import the computer.json file.

Any idea why? 

Thanks in advance!

**Comment by enj5oy** [comment]
@Hexix23 which neo4j version you use?

**Comment by Hexix23** [comment]
@enj5oy I tried 4.4.30/4.4.32

**Comment by enj5oy** [comment]
@Hexix23 try neo4j 4.4.26 or try to use this project https://github.com/pastebt/shred maybe you have corrupted object in json file

**Comment by Hexix23** [comment]
I have:
- neo4j 4.4.26
- bofhound 0.2.0
- pyldapsearch 0.1.3
- bloodhound 4.3.1

And is not working, and the computer.json is only 21KB :(

**Comment by enj5oy** [comment]
> I have:
> 
> * neo4j 4.4.26
> * bofhound 0.2.0
> * pyldapsearch 0.1.3
> * bloodhound 4.3.1
> 
> And is not working, and the computer.json is only 21KB :(
Which commit for bofhound you use?
 I verified in my setup that the computers.json uploads without any issues today

**Comment by Hexix23** [comment]
Im using the last version of it. I downloaded directly from the Release
Page.

If you don’t mind, can you confirm if u can ingest the data using
pyldapsearch? Maybe is that sir

**Comment by Hexix23** [comment]
Or if you don't mind, can you share the commit that you are using?

Thanks in advance

**Comment by Hexix23** [comment]
> > I have:
> > 
> > * neo4j 4.4.26
> > * bofhound 0.2.0
> > * pyldapsearch 0.1.3
> > * bloodhound 4.3.1
> > 
> > And is not working, and the computer.json is only 21KB :(
> 
> Which commit for bofhound you use? I verified in my setup that the computers.json uploads without any issues today

Im using the last version of it. I downloaded directly from the Release
Page.

If you don’t mind, can you confirm if u can ingest the data using
pyldapsearch? Maybe is that sir

Or if you don't mind, can you share the commit that you are using?

Thanks in advance

**Comment by enj5oy** [comment]
@Hexix23 
Pyldapsearch latest version
Bofhound, this commit
https://github.com/coffeegist/bofhound/commit/4a97823ebc34510b04e2fa6268c8d3d11ac4003d

**Comment by boringthegod** [comment]
with bofhound v0.4.0
BloodHound 4.3.1
neo4j 4.4.26

computers.json can't be import

**Comment by boringthegod** [comment]
ok thanks
